name: Publish new documentation
on:
  push:
    branches:
      - main
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-macros-plugin mkdocs-minify-plugin mkdocs-glightbox
      - run: mkdocs gh-deploy --force