name: Publish new documentation
on:
  push:
    branches:
      - main
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.sonatype_username }}
          MAVEN_PASSWORD: ${{ secrets.sonatype_password }}
      - name: Build documentation with Dokka
        run: |
          ./gradlew :modules:dokkaHtmlMultiModule
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Get cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install necessary pip package
        run: pip install mkdocs-material mkdocs-macros-plugin mkdocs-minify-plugin mkdocs-glightbox pillow cairosvg
      - name: Deploy documentation with mkdocs
        run: mkdocs gh-deploy --force